### ISSUE TITLE
Liquid Mixer UI

### ISSUE THREAD

**Issue by stasbar** [vape-tool/VapeTool-Webapp#31]
![Screenshot_20200515-123543](https://user-images.githubusercontent.com/9407590/82041609-babf6900-96a8-11ea-968f-58c84c8186fa.png)
Blocked by #30

**Comment by stasbar** [comment]
@gbaranski can you handle it ?

**Comment by gbaranski** [comment]
> @gbaranski can you handle it ?

Of course :)
