### ISSUE TITLE
Help coil calculator

### ISSUE THREAD

**Issue by stasbar** [vape-tool/VapeTool-Webapp#47]
![coil_help](https://user-images.githubusercontent.com/9407590/78156156-ad268a80-743e-11ea-9b21-db56451e3c93.png)

**Comment by gbaranski** [comment]
hello i will do this in javascript

**Comment by stasbar** [comment]
## Coil type
<string name="tutorial_setup_and_coil_type">Setup and coil type</string>
<string name="tutorial_setup_and_coil_type_description">First of all select how many coil you want to build and what type you want to build</string>
![tutorial_coil_type](https://user-images.githubusercontent.com/9407590/83946535-b7d01800-a811-11ea-865d-2a20b113ad5d.jpg)

## Wires Section
<string name="tutorial_wires_section_title">Wires section</string>
<string name="tutorial_wires_section_title_description">Adjust the parameters of the wires, if you want to add more wires to your build press \" + \" button (You can\'t add more wires in every type )</string>
![tutorial_wires_wizzard](https://user-images.githubusercontent.com/9407590/83946549-db935e00-a811-11ea-962f-f4b52c5680aa.jpg)

## Inner diameter
<string name="text_view_inner_diameter">Inner diameter of coil</string>
<string name="help_inner_diameter">This is diameter of drill on which you are wrapping your coil</string>
![tutorial_inner_diameter](https://user-images.githubusercontent.com/9407590/83946563-f534a580-a811-11ea-9281-787b430cc9ec.jpg)

## Legs length
<string name="text_view_legs_length">Legs length per coil</string>
<string name="help_legs_length">Legs Length is the wire length between wraps on coil edge and pins in atomizer.  Remember to enter length of both legs, like on picture above</string>
![tutorial_legs_length](https://user-images.githubusercontent.com/9407590/83946586-14cbce00-a812-11ea-93ab-96910c71b4c5.jpg)

##  Wraps
<string name="text_view_wraps">Number of wraps per coil</string>
<string name="help_wraps">If legs go in the same direction (In most RDAs), there are two half wraps on both coil edges, so they are also counted in half.
        \n In picture above there are 5 wraps, not 6 !
        \n(4 full wraps, and 2 half wraps) </string>
    
![tutorial_wraps](https://user-images.githubusercontent.com/9407590/83946612-40e74f00-a812-11ea-9ffa-8550017b72ad.jpg)
