### ISSUE TITLE
Preview user saved Coils, Liquids, Flavors on user page

### ISSUE THREAD

**Issue by stasbar** [vape-tool/VapeTool-Webapp#63]
![SavedCoilCollections (1)](https://user-images.githubusercontent.com/9407590/78154459-94b57080-743c-11ea-961e-9253112bed78.png)
![LiquidRecipeCollection (1)](https://user-images.githubusercontent.com/9407590/78154462-954e0700-743c-11ea-81c7-a9d39c465483.png)
![FlavorCollection (1)](https://user-images.githubusercontent.com/9407590/78154466-967f3400-743c-11ea-9695-481d6ca62227.png)

**Comment by gbaranski** [comment]
Hello, I will do it :)

**Comment by gbaranski** [comment]
closed by #70
