### ISSUE TITLE
Fix styling

### ISSUE THREAD

**Issue by stasbar** [vape-tool/VapeTool-Webapp#84]
<img width="238" alt="Screenshot 2020-08-18 at 21 59 37" src="https://user-images.githubusercontent.com/9407590/90559635-28929980-e19e-11ea-976f-d93d7f1f253a.png">

This look like shit. Fix alignments and/or margins. (on all pages, not only Liquid Blender)
<img width="766" alt="Screenshot 2020-08-18 at 21 59 35" src="https://user-images.githubusercontent.com/9407590/90559638-2af4f380-e19e-11ea-9b51-858d76100f9e.png">

**Comment by gbaranski** [comment]
thats already fixed
