### ISSUE TITLE
Hide stable/max vaping resistances from anonymous and non-pro users

### ISSUE THREAD

**Issue by stasbar** [vape-tool/VapeTool-Webapp#88]
<img width="475" alt="Screenshot 2020-09-08 at 14 13 52" src="https://user-images.githubusercontent.com/9407590/92475467-b847c880-f1dd-11ea-948f-061281b599ab.png">

**Comment by stasbar** [comment]
<img width="206" alt="Screenshot 2020-09-08 at 14 18 58" src="https://user-images.githubusercontent.com/9407590/92475780-3f953c00-f1de-11ea-8fb4-f665796bcfcb.png">
Similar to this

**Comment by gbaranski** [comment]
closed by #99
