### ISSUE TITLE
Fix ads

### ISSUE THREAD

**Issue by stasbar** [vape-tool/VapeTool-Webapp#90]
Coil calculator show this 
<img width="95" alt="Screenshot 2020-09-08 at 14 20 40" src="https://user-images.githubusercontent.com/9407590/92475994-913dc680-f1de-11ea-9f35-662efc74dfd7.png">

Clicking on ad should open the page in new tab

Add ads to Cloud

**Comment by gbaranski** [comment]
@stasbar it would work if the admob linkUrl wouldnt be empty.

**Comment by gbaranski** [comment]
look 
```ts
        <a href={bannerProperties.linkUrl}>
          <img src={bannerSrc} alt={bannerProperties.name} />
        </a>
```
